### ISSUE TITLE
Suggestions for Loop detection feature

### ISSUE THREAD

**Issue by italovalcy** [kytos-ng/of_lldp#48]
Some comments regarding the loop detection feature merged on PR #36:

1) In the code https://github.com/kytos-ng/of_lldp/blob/master/loop_manager.py#L314-L320

When we have successive updates on the `switch.metadata.ignored_loops` we can end up removing the `self.ignored_loops` settings. It seems to be an undesired behavior. Can you please check that?

I'm using the following topology:

```
#  cat mytopo.py
from mininet.topo import Topo
from mininet.link import Link

class MyTopo( Topo ):
    def build( self ):
        # Add hosts and switches
        h1 = self.addHost('h1')
        h2 = self.addHost('h2')
        s1 = self.addSwitch('s1')
        # Add links
        self.addLink(s1, h1)
        self.addLink(s1, h2)
        self.addLink(s1, s1, port1=3, port2=4)
        self.addLink(s1, s1, port1=5, port2=6)


topos = { 'mytopo': ( lambda: MyTopo() ) }

# mn --custom mytopo.py --topo mytopo --controller=remote,ip=127.0.0.1
```

I've also changed `of_lldp.settings.LOOP_LOG_EVERY` to 20.

It begins alerting about all loops as expected:

```
Apr  4 20:53:26 331f4f85c855 kytos.napps.kytos/of_lldp:WARNING loop_manager:280:  LLDP loop detected on switch: 00:00:00:00:00:00:00:01, interfaces: ['s1-eth5', 's1-eth6'], port_numbers: [5, 6]
Apr  4 20:54:27 331f4f85c855 kytos.napps.kytos/of_lldp:WARNING loop_manager:280:  LLDP loop detected on switch: 00:00:00:00:00:00:00:01, interfaces: ['s1-eth3', 's1-eth4'], port_numbers: [3, 4]
Apr  4 20:54:27 331f4f85c855 kytos.napps.kytos/of_lldp:WARNING loop_manager:280:  LLDP loop detected on switch: 00:00:00:00:00:00:00:01, interfaces: ['s1-eth5', 's1-eth6'], port_numbers: [5, 6]
Apr  4 20:55:28 331f4f85c855 kytos.napps.kytos/of_lldp:WARNING loop_manager:280:  LLDP loop detected on switch: 00:00:00:00:00:00:00:01, interfaces: ['s1-eth3', 's1-eth4'], port_numbers: [3, 4]
```

Then I changed the switch metadata to add one ignored loop:

```
curl -H 'Content-type: application/json' -X POST http://127.0.0.1:8181/api/kytos/topology/v3/switches/00:00:00:00:00:00:00:01/metadata -d '{"ignored_loops": [[3, 4]]}'
```

After that, the loop manager correctly stop reporting the first loop:

```
Apr  4 20:55:28 331f4f85c855 kytos.napps.kytos/of_lldp:WARNING loop_manager:280:  LLDP loop detected on switch: 00:00:00:00:00:00:00:01, interfaces: ['s1-eth5', 's1-eth6'], port_numbers: [5, 6]
Apr  4 20:56:29 331f4f85c855 kytos.napps.kytos/of_lldp:WARNING loop_manager:280:  LLDP loop detected on switch: 00:00:00:00:00:00:00:01, interfaces: ['s1-eth5', 's1-eth6'], port_numbers: [5, 6]
Apr  4 20:57:30 331f4f85c855 kytos.napps.kytos/of_lldp:WARNING loop_manager:280:  LLDP loop detected on switch: 00:00:00:00:00:00:00:01, interfaces: ['s1-eth5', 's1-eth6'], port_numbers: [5, 6]
```

Then I change the metadata to add more ignored loops:

```
curl -H 'Content-type: application/json' -X POST http://127.0.0.1:8181/api/kytos/topology/v3/switches/00:00:00:00:00:00:00:01/metadata -d '{"ignored_loops": [[3, 4], [5, 6]]}'
```

And then loop manager start reporting everything back:

```
Apr  4 20:58:25 331f4f85c855 kytos.napps.kytos/of_lldp:WARNING loop_manager:280:  LLDP loop detected on switch: 00:00:00:00:00:00:00:01, interfaces: ['s1-eth3', 's1-eth4'], port_numbers: [3, 4]
Apr  4 20:58:31 331f4f85c855 kytos.napps.kytos/of_lldp:WARNING loop_manager:280:  LLDP loop detected on switch: 00:00:00:00:00:00:00:01, interfaces: ['s1-eth5', 's1-eth6'], port_numbers: [5, 6]
Apr  4 20:59:25 331f4f85c855 kytos.napps.kytos/of_lldp:WARNING loop_manager:280:  LLDP loop detected on switch: 00:00:00:00:00:00:00:01, interfaces: ['s1-eth3', 's1-eth4'], port_numbers: [3, 4]
Apr  4 20:59:32 331f4f85c855 kytos.napps.kytos/of_lldp:WARNING loop_manager:280:  LLDP loop detected on switch: 00:00:00:00:00:00:00:01, interfaces: ['s1-eth5', 's1-eth6'], port_numbers: [5, 6]
Apr  4 21:00:26 331f4f85c855 kytos.napps.kytos/of_lldp:WARNING loop_manager:280:  LLDP loop detected on switch: 00:00:00:00:00:00:00:01, interfaces: ['s1-eth3', 's1-eth4'], port_numbers: [3, 4]
Apr  4 21:00:33 331f4f85c855 kytos.napps.kytos/of_lldp:WARNING loop_manager:280:  LLDP loop detected on switch: 00:00:00:00:00:00:00:01, interfaces: ['s1-eth5', 's1-eth6'], port_numbers: [5, 6]
```

2) In the code https://github.com/kytos-ng/of_lldp/blob/master/main.py#L127

Instead of returning on the first failure, what do you think about logging all the failures but keep trying to publish other stopped loops? I mean: we could use the `log.error` with the specific `port_pairs` and `dpid` (instead of all items) and do not return right away. Wdyt?

3) In the code https://github.com/kytos-ng/of_lldp/blob/master/settings.py#L11

maybe we should add a note here to alert the user that this will be overwritten by switch.metadata.ignored_loops if that exists.

4) In the code https://github.com/kytos-ng/of_lldp/blob/master/settings.py#L12

I think the default will be 100s, no? Considering the default POLLING_TIME of 3s?

Another thing is: I've changed the LOOP_LOG_EVERY to 20s and the log entries are being generated every 60s anyway.

**Comment by viniarck** [comment]
> 1 - When we have successive updates on the switch.metadata.ignored_loops we can end up removing the self.ignored_loops settings. It seems to be an undesired behavior. Can you please check that?

Good catch, @italovalcy, it's a major bug, I've just assigned this issue, I'll fix this. 

> 2 - Instead of returning on the first failure, what do you think about logging all the failures but keep trying to publish other stopped loops?

It's a great a idea, let's go for it. 

> 3 - Maybe we should add a note here to alert the user that this will be overwritten by switch.metadata.ignored_loops if that exists.

Yeah, that'd b helpful, I'll add a comment. 

> 4 - I think the default will be 100s, no? Considering the default POLLING_TIME of 3s?

That's right, the default value ended up wrong, I'll fix this too. 

Thanks for reporting this, Italo.
